New petition's page (Issue 96)
itsriodejaneiro/mudamos-web pull request #131
Opened 2017-01-26 18:46 UTC by erickzanardo

This PR closes #97 

### How was it before?

- the application had a totally different petition's page from the mobile app

### What has changed?

- that page now has been refactored to have a simular look of the mobile app
- the page is responsive and can ajust itself to a desktop, tablet and smartphone viewports

### What should I pay attention when reviewing this PR?

Nothing special

### Is this PR dangerous?

no

2017-01-26 20:14 UTC, guimello requested changes

2017-01-26 20:14 UTC, guimello commented on app/assets/javascripts/progress-bar.js
> +    $container.append($currentPercentageBar);
Have you tested this using a multiple node selector? Not sure that this will work, usually we do this with `#each` in order to handle this.

Another issue this is that jQuery plugins should return `this` so one can chain method calls.

2017-01-26 20:14 UTC, guimello commented on app/assets/stylesheets/petition.sass
> +  .rounded-button
Shouldn't this be extract outside this page? It seems pretty reusable.

2017-01-26 20:14 UTC, guimello commented on app/assets/stylesheets/petition.sass
> +@media (max-device-width: 839px)
Why not use bootstrap own breakpoints for this? They already define variables for this kind of situation.

2017-01-26 20:14 UTC, guimello commented on app/models/cycle.rb
> +    rgb = color.scan(/[a-fA-F0-9]{2}/).map { |color| color.to_i(16) }
I guess this is a presentation concern. You could put this method in a module and use it passing both the color and alpha desired.

2017-01-26 20:22 UTC, marcoamarelo approved these changes
PR Accepted!

2017-01-27 11:20 UTC, erickzanardo commented on app/assets/stylesheets/petition.sass
> +@media (max-device-width: 839px)
I did not understood, bootstrap has media queries for it's grid system, which we are already using, this media query is meant to customize the page when it is a tablet, things height, position and etc, the responsive business is all dealt by bootstrap.

2017-01-27 11:29 UTC, guimello commented on app/assets/stylesheets/petition.sass
> +@media (max-device-width: 839px)
http://getbootstrap.com/css/#grid-media-queries

2017-01-27 11:34 UTC, guimello commented on app/controllers/cycles/plugin_relations_controller.rb
> +  def color_as_rgba(color, alpha)
I think this method does not belong to the controller either. What if I'm writing an email body and need to convert a hex color to rgba?

I think this belongs to a view helper (in Rails) but what I mean is any other module helper. Which I can use wherever I want.

2017-01-27 12:02 UTC, guimello approved these changes

2017-01-27 12:08 UTC, merged