Add FAQ
itsriodejaneiro/mudamos-web pull request #482
Opened 2019-05-22 18:50 UTC by caioitiroko

This PR closes #481 .

**How was it before?**
FAQs didn't exists.

**What has changed?**
- Add a CRUD FAQ
- Add a page to show FAQs
- Add FAQ link on menu 

**This PR is dangerous?**
No

**Should I pay attention to this PR?**
Nothing in particular

2019-05-23 12:17 UTC, guimello requested changes
Looking good

2019-05-23 12:17 UTC, guimello commented on app/assets/stylesheets/admin/global.sass
> +  .card-module
Eu adicionaria uma linha em branco toda vez que vc muda de selector (para facilitar a leitura):

```
.admin-xxx
  color: white

  .faq-thumb
     color: red;
```

2019-05-23 12:17 UTC, guimello commented on app/assets/stylesheets/admin/global.sass
> +    z-index: 1
Vou perguntar pq é difícil fazer o code review nestes casos. Você tentou posicionar o DOM para que não precisasse mudar `z-index`?

Sei que muitas vezes não tem outra forma.

2019-05-23 12:17 UTC, guimello commented on app/assets/stylesheets/admin/global.sass
> +    -webkit-background-size: cover
Você pode criar um `mixin` igualzinho vc fez outra vez para gerar isso.

2019-05-23 12:17 UTC, guimello commented on app/controllers/admin/faqs_controller.rb
> +    @faq = Faq.find params[:id]
Lembre-se, se for um `assignment`, nosso guideline é usar parênteses.
```
@faq = Faq.find(params[:id])
```

2019-05-23 12:17 UTC, guimello commented on app/controllers/admin/faqs_controller.rb
> +    @faq = Faq.new faq_params
parênteses

2019-05-23 12:17 UTC, guimello commented on app/views/admin/faqs/show.html.slim
> +      = "Criado em #{@faq.created_at.strftime('%d/%m/%Y')}"
Prefira `I18n.l`

2019-05-23 12:17 UTC, guimello commented on db/migrate/20190507130540_create_faqs.rb
> +      t.integer :sequence
Adicione o index no `sequence`, vc sempre ordena por ele.

2019-05-23 12:17 UTC, guimello commented on spec/controllers/admin/faqs_controller_spec.rb
> +require 'rails_helper'
remova todas esses specs já que não vai ter teste

2019-05-30 12:44 UTC, caioitiroko commented on app/assets/stylesheets/admin/global.sass
> +    z-index: 1
Neste caso precisa por conta de outros componentes que sobrepõem esse elemento

2019-05-30 13:19 UTC, guimello approved these changes

2019-05-30 13:19 UTC, guimello commented on app/assets/stylesheets/admin/global.sass
> +  .faq-actions-card
Por que não pulou linha nessas partes?

2019-05-31 12:34 UTC, merged