Edition of Petition information on admin
itsriodejaneiro/mudamos-web pull request #59
Opened 2017-01-04 18:23 UTC by erickzanardo

This PR closes #54 by implementing of the edition page of the petition information

### How was it before?

- petition information was mocked

### What has changed?

- the mocking on the admin pages of the petition was removed and replaced by functional pages

### What should I pay attention when reviewing this PR?

Nothing special.

### Is this PR dangerous?

No.

2017-01-04 19:27 UTC, marcoamarelo commented
PR accepted!

2017-01-05 11:10 UTC, guimello requested changes
I'm not particular happy with the way we are going with this because this is not going to work. on the other hand this is what the issue was telling you to do.

I think we should file a new ticket to version the petition because the mobile api will need it.

For now, I guess it is okay to proceed.

I'm requesting changes mainly because of the `presentation` attr being `string` and not `text`.

2017-01-05 11:10 UTC, guimello commented on app/controllers/admin/cycles/plugin_relations/petitions_controller.rb
> +      flash[:error] = "Ocorreu algum erro ao criar a petição."
`atualizar`

2017-01-05 11:10 UTC, guimello commented on app/controllers/admin/cycles/plugin_relations/petitions_controller.rb
> +    @petition = PetitionPlugin::Information.new.tap { |i| i.plugin_relation_id = @plugin_relation.id }
Not sure why use `#tap` here. You could always pass attributes to the constructor.

```
Info.new(plugin_relation_id: @plugin_relation.id)
```

2017-01-05 11:10 UTC, guimello commented on app/views/admin/cycles/plugin_relations/petitions/_form.html.slim
> +      = f.input :document_url, as: :url, label: 'URL do documento'
Actually this is not editable. The system will provide this url. When saving the `body` attribute, in the future we will build a pdf version of it, upload to the s3 when save the `document_url`.

But for now I guess it is okay this way.

2017-01-05 11:10 UTC, guimello commented on app/views/admin/cycles/plugin_relations/petitions/_form.html.slim
> +  javascript:
No need to add javascript like this. You could generalize this and include a file in asset pipeline. On document ready you can initialize all markdown elements using a class.

2017-01-05 11:10 UTC, guimello commented on db/migrate/20170103194805_create_petition_information.rb
> +      t.string :presentation, null: false
I believe presentation is like a `text`. And on the edit view it should be a `textarea`.

2017-01-05 11:10 UTC, guimello commented on db/migrate/20170103194805_create_petition_information.rb
> +      t.string :document_url, null: false
As I explained this will not work in the future, but I lot more won't work either because of document versioning  :/

2017-01-05 13:47 UTC, guimello approved these changes
🚀

2017-01-05 13:48 UTC, merged